services:
  postgres:
    image: postgres:16
    container_name: ecommerce_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce_analytics
    ports:
      - "5432:5432"
    volumes:
    - ./postgres/init_schema.sql:/docker-entrypoint-initdb.d/01_init_schema.sql
    - ../data/raw:/data/raw
  localstack:
    image: localstack/localstack:latest
    container_name: ecommerce_localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1